[pytest]
python_files = test_*.py *_test.py tests.py
python_classes = Test*
python_functions = test_*
addopts = 
    --tb=short
    --strict-markers
    -v
testpaths = .
norecursedirs = .git build dist .venv venv __pycache__ *.egg-info

[coverage:run]
source = .
omit = 
    .venv/*
    build/*
    test_*.py
    *_test.py
    utils/test_*.py
    main.py
    setup.py

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:
    @abstractmethod
    @abstractproperty
precision = 2

